language: node_js
node_js: stable
branchs:
  only:
  - hexo
cache:
  directories:
  - node_modules
before_install:
# 安装hexo-cli
- npm install -g hexo-cli
install:
# 安装依赖包
- sudo apt-get update
- sudo apt-get install -y graphicsmagick
- npm install
script:
- hexo g

after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config --global user.email "i@kkren.me"
- git config --global user.name "kkren" 
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
    global:
        - GH_REF: github.com/kkren/kkren.github.io.git 