language: node_js
node_js: stable
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
# 安装hexo-cli
- npm install -g hexo-cli
install:
# 安装依赖包
- apt-get install imagemagick
- npm install
script:
# 生成静态文件
- hexo clean
- hexo g
after_success:
# push到vps仓库
- cd ./public
- git init
- git config user.name "kkren"
- git config user.email "i@kkren.me"
- git add .
- git commit -m "deploy blog"
- git push "git@vps:blog.git" master:master